name: Teletype
version: '${version}'

main: io.github.Earth1283.teletype.Teletype
api-version: '1.21'
load: STARTUP

authors: [ Earth1283 ]

commands:
  tty:
    description: Teletype web server control
    usage: /tty <verify|status|start|stop>
    permission: teletype.admin

permissions:
  teletype.admin:
    description: Full Teletype admin access
    default: op
